### ISSUE TITLE
2.7.0 not working for strange reason

### ISSUE THREAD

**Issue by m-messiah** [valeriangalliat/markdown-it-anchor#23]
Hello, I have your package as dependency of aglio-theme-olio,

When I try to gulp build, I have a strange error:
```
/build/proj/api/node_modules/markdown-it-anchor/index.js:79
      var slug = token.attrGet('id');
                       ^

TypeError: token.attrGet is not a function
    at /build/proj/api/node_modules/markdown-it-anchor/index.js:79:24
    at Array.forEach (native)
    at Array.<anonymous> (/build/proj/api/node_modules/markdown-it-anchor/index.js:71:8)
    at Core.process (/build/proj/api/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/build/proj/api/node_modules/markdown-it/lib/index.js:493:13)
    at MarkdownIt.render (/build/proj/api/node_modules/markdown-it/lib/index.js:513:36)
    at decorate (/build/proj/api/node_modules/aglio-theme-olio/lib/main.js:404:32)
    at Object.exports.render (/build/proj/api/node_modules/aglio-theme-olio/lib/main.js:646:5)
    at /build/proj/api/node_modules/aglio/lib/main.js:133:20
```
If I force install 2.6.0 version - all works ok.

**Comment by kadishmal** [comment]
:) See #24, too. We've been bitted by this at the same time.

**Comment by valeriangalliat** [comment]
Sorry for this, see my comment on #24 :)
