### ISSUE TITLE
TypeError: require(...).use is not a function

### ISSUE THREAD

**Issue by xcatliu** [valeriangalliat/markdown-it-anchor#26]
I use it as the README.md said, but got such errors:

```
const md = require('markdown-it').use(require('markdown-it-anchor'))({
                                  ^

TypeError: require(...).use is not a function
    at Object.<anonymous> (D:\workspace\mobi.css\gulpfile.js:15:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (D:\workspace\mobi.css\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (D:\workspace\mobi.css\node_modules\liftoff\index.js:198:16)
```

I think the README.md should update to something like this:

```js
const md = require('markdown-it')()
  .use(require('markdown-it-anchor'), opts)
```

**Comment by valeriangalliat** [comment]
Good catch, thank you!
